julianpoy/RecipeSage

- Backend/package-lock.json
- Backend/package.json
- Backend/src/routes/clip.js
> fix: decode html entities

- Backend/package-lock.json
- Backend/package.json
- Backend/src/routes/mealPlans.js
- Frontend/src/app/app.scss
- Frontend/src/app/pages/info-components/release-notes/release-notes.page.html
- Frontend/src/app/pages/meal-plan-components/meal-plan-popover/meal-plan-popover.page.html
- Frontend/src/app/pages/meal-plan-components/meal-plan-popover/meal-plan-popover.page.ts
- Frontend/src/app/pages/meal-plan-components/share-meal-plan-modal/share-meal-plan-modal.module.ts
- Frontend/src/app/pages/meal-plan-components/share-meal-plan-modal/share-meal-plan-modal.page.html
- Frontend/src/app/pages/meal-plan-components/share-meal-plan-modal/share-meal-plan-modal.page.ts
- Frontend/src/assets/i18n/en-us.json
> feat: ICS/iCal meal plan sharing

- SharedUtils/src/index.js
> fix: Empty ingredient lines are parsed as ingredient entries

- Backend/package-lock.json
- Backend/package.json
- Backend/src/middleware/joiValidator.js
- Backend/src/migrations/20221022000000-add-notnull-shopping-list-item-completed.js
- Backend/src/routes/shoppingLists.js
- Frontend/src/app/components/shopping-list-group/shopping-list-group.component.html
- Frontend/src/app/components/shopping-list-group/shopping-list-group.component.ts
- Frontend/src/app/components/shopping-list-item/shopping-list-item.component.html
- Frontend/src/app/components/shopping-list-item/shopping-list-item.component.ts
- Frontend/src/app/pages/shopping-list-components/shopping-list-popover/shopping-list-popover.page.html
- Frontend/src/app/pages/shopping-list-components/shopping-list/shopping-list.page.html
- Frontend/src/app/pages/shopping-list-components/shopping-list/shopping-list.page.ts
- Frontend/src/app/services/preferences.service.ts
- Frontend/src/app/services/shopping-list.service.ts
- Frontend/src/assets/i18n/en-us.json
- Frontend/src/assets/i18n/it-it.json
This replaces the default behavior of marking items as completed. Previously, items would be immediately removed. Now, items are marked as completed and shown in a section below all of the incomplete items.
There is a toggle in the popover for the shopping list page that allows users to re-enable the previous behavior.
> feat: support for marking shopping list items as completed

- Backend/src/routes/images.js
Fixes forever pending request when no image is specified for upload.
> fix: no image upload

- Frontend/src/app/pages/recipe-components/recipe/recipe.page.html
- Frontend/src/app/services/util.service.ts
> feat: truncate max length for URL preview

- Frontend/src/app/services/preferences.service.ts
- Frontend/src/assets/i18n/de-de.json
Based on the changes from #813 thanks to @chschr
> feat: de-de support

- Backend/src/views/recipe-default.pug
- Frontend/src/app/pages/recipe-components/print-recipe-modal/print-recipe-modal.page.ts
This PR fixes a number of issues introduced by the v2.9.x series:
1. The print text size
2. The print previews not showing up
3. The print not reflecting the current scale
> fix: recipe printing

- Frontend/src/app/pages/social/profile/profile.page.ts
> fix: view profile while logged out

- Frontend/src/app/components/meal-calendar/calendar-item/calendar-item.component.html
> fix: meal plan items do not reflect updated recipe title

- Backend/src/routes/images.js
- Backend/src/routes/labels.js
- Backend/src/routes/mealPlans.js
- Backend/src/routes/messages.js
- Backend/src/routes/payments.js
- Backend/src/routes/print.js
- Backend/src/routes/recipes.js
- Backend/src/routes/shoppingLists.js
- Backend/src/routes/users.js
- Backend/src/services/subscriptions.js
- Backend/src/utils/errors.js
- Backend/src/utils/wrapRequestWithErrorHandler.js
- Migrates all routes to async/await
- Error handler wrapper for all routes
- Reusable HTTP errors
- Fix some issues with some routes returning responses before transactions were persisted (Closes #710)
> feat: async/await for all routes

- Backend/src/routes/mealPlans.js
> fix: meal plan collaborator delete

- Backend/src/emails/welcome.js
- Frontend/src/app/components/social-links/social-links.component.html
- Frontend/src/app/pages/info-components/about-details/about-details.page.html
- Frontend/src/app/pages/info-components/about/about.page.html
- Frontend/src/app/pages/info-components/contact/contact.page.html
- Frontend/src/assets/i18n/de-de.json
- Frontend/src/assets/i18n/en-us.json
- Frontend/src/assets/i18n/it-it.json
Directs users to documentation at common "contact" points, in an attempt to decrease the number of emails about common questions.
> feat: please use docs

- Backend/src/routes/mealPlans.js
- Backend/src/routes/shoppingLists.js
> fix: creating shopping lists and meal plans

- Backend/src/migrations/20221226000000-image-userid-nullable.js
- Backend/src/routes/recipes.js
- Backend/src/routes/users.js
- Backend/src/services/s3-storage.js
- Backend/src/utils/data/deleteHangingImages.js
- Frontend/src/app/pages/settings-components/account/account.page.html
- Frontend/src/app/pages/settings-components/account/account.page.ts
- Frontend/src/app/services/user.service.ts
- Frontend/src/assets/i18n/de-de.json
- Frontend/src/assets/i18n/en-us.json
- Frontend/src/assets/i18n/it-it.json
> feat: native account deletion

- Frontend/package-lock.json
- Frontend/package.json
Reverts julianpoy/RecipeSage#972
Causes dependency resolution issues :(
> Revert "chore: install @julianpoy/ngx-translate-lint as devdep"

- Frontend/src/app/app.scss
- Frontend/src/app/components/select-knownuser/select-knownuser.component.html
- Frontend/src/app/components/select-knownuser/select-knownuser.component.ts
- Frontend/src/app/components/select-knownuser/select-knownuser.module.ts
- Frontend/src/app/components/select-user-knownuser/select-user-knownuser.component.html
- Frontend/src/app/components/select-user-knownuser/select-user-knownuser.component.ts
- Frontend/src/app/components/select-user-knownuser/select-user-knownuser.module.ts
- Frontend/src/app/components/select-user/select-user.component.html
- Frontend/src/app/components/select-user/select-user.component.ts
- Frontend/src/app/pages/recipe-components/recipe/recipe.page.html
- Frontend/src/app/pages/recipe-components/recipe/recipe.page.ts
- Frontend/src/app/pages/settings-components/account/account.page.ts
- Frontend/src/app/pages/share-modal/share-modal.module.ts
- Frontend/src/app/pages/share-modal/share-modal.page.html
- Frontend/src/app/pages/share-modal/share-modal.page.ts
- Frontend/src/app/services/user.service.ts
- Frontend/src/assets/i18n/de-de.json
- Frontend/src/assets/i18n/en-us.json
- Frontend/src/assets/i18n/it-it.json
> feat: use select-user component for share modal

- Frontend/src/app/app.module.ts
Reverts julianpoy/RecipeSage#981
> Revert "fix: use custom translate loader"

- Frontend/tsconfig.json
Reverts julianpoy/RecipeSage#987
> Revert "fix: old browser support"

- docker-compose.yml
- packages/backend/Dockerfile
- packages/backend/src/bin/www.js
- packages/backend/src/routes/recipes.js
- packages/backend/src/routes/users.js
- packages/backend/src/services/search/elasticsearch.ts
- packages/backend/src/services/search/index.ts
- packages/backend/src/services/search/meilisearch.ts
- scripts/watchandrun.sh
> feat: Elasticsearch improvements

- packages/frontend/src/app/pages/auth/auth.page.html
- packages/frontend/src/app/pages/auth/auth.page.ts
> fix: display close button when auth is in modal

- packages/backend/src/routes/data.js
- packages/backend/src/services/json-ld.js
> fix: selfhost image export import

- .circleci/config.yml
- packages/backend/Dockerfile
- packages/frontend/selfhost.Dockerfile
- scripts/build/api-selfhost.sh
- scripts/build/webapp-selfhost.sh
armv7 is not supported by sharp https://github.com/lovell/sharp/issues/3150
> fix: remove armv7 and build frontend outside container

- packages/trpc/src/dbHelpers/getFriendshipIds.ts
- packages/trpc/src/dbHelpers/getFriendshipUsers.ts
- packages/trpc/src/dbHelpers/getRecipesWithConstraints.ts
- packages/trpc/src/procedures/recipes/getRecipes.ts
- packages/trpc/src/procedures/recipes/searchRecipes.ts
Fetches only friendship ids rather than full profiles. Could be trimmed further by reusing the friendship query, but complicates the code a bit. Kept it simple for now, since the performance is pretty good for now.
> fix: improve getRecipes and searchRecipes perf

- packages/frontend/src/app/components/meal-calendar/meal-calendar.component.ts
> fix: meal plan multiple day selection

- packages/frontend/src/app/pages/social/add-profile-item-modal/add-profile-item-modal.page.html
- packages/frontend/src/assets/i18n/en-us.json
> fix: profile item visibility selector preview

- packages/frontend/src/app/app.component.html
- packages/frontend/src/app/app.scss
> fix: elements covered by pinned recipes toolbar

- packages/frontend/src/app/pages/recipe-components/recipe/recipe.page.html
- packages/frontend/src/app/pages/recipe-components/recipe/recipe.page.scss
- packages/frontend/src/app/pages/recipe-components/recipe/recipe.page.ts
> fix: do not display recipe details contents until loaded

- packages/frontend/src/app/components/select-ingredients/select-ingredients.component.ts
- packages/frontend/src/app/pages/shopping-list-components/shopping-list-ignore-modal/shopping-list-ignore-modal.module.ts
- packages/frontend/src/app/pages/shopping-list-components/shopping-list-ignore-modal/shopping-list-ignore-modal.page.html
- packages/frontend/src/app/pages/shopping-list-components/shopping-list-ignore-modal/shopping-list-ignore-modal.page.ts
- packages/frontend/src/app/pages/shopping-list-components/shopping-lists/shopping-lists.page.html
- packages/frontend/src/app/pages/shopping-list-components/shopping-lists/shopping-lists.page.ts
- packages/frontend/src/app/services/preferences.service.ts
- packages/frontend/src/assets/i18n/de-de.json
- packages/frontend/src/assets/i18n/en-us.json
- packages/frontend/src/assets/i18n/he.json
- packages/frontend/src/assets/i18n/it-it.json
- packages/frontend/src/assets/i18n/uk-ua.json
> feat: allow users to specify excluded shopping list items

- packages/backend/src/services/json-ld.js
> feat: include identifier in JSON-LD export

- packages/backend/src/routes/index.js
> fix: indexRecipes error on some imports

- packages/trpc/src/services/chat/openai.ts
Fixes issues where openai key might not be defined in CI such as for contributor PRs.
> chore: disable openai in test env

- packages/backend/src/routes/users.js
Closes https://github.com/julianpoy/RecipeSage-selfhost/issues/67
> fix: check DISABLE_REGISTRATION against 'true'

- packages/frontend/src/assets/i18n/fr-fr.json
Translations update from [RecipeSage Weblate](http://weblate.recipesage.com) for [RecipeSage App/Frontend UI](http://weblate.recipesage.com/projects/recipesage-app/app-frontend/).
Current translation status:
> chore: translations update from weblate.recipesage.com

- packages/frontend/src/app/services/util.service.ts
- packages/frontend/src/assets/i18n/ru-ru.json
- packages/util/src/preferences.ts
> feat: ru-ru translation

- packages/frontend/src/assets/i18n/ru-ru.json
Translations update from [RecipeSage Weblate](http://weblate.recipesage.com) for [RecipeSage App/Frontend UI](http://weblate.recipesage.com/projects/recipesage-app/app-frontend/).
Current translation status:
> fix(l10n): translations update from weblate.recipesage.com

- packages/backend/src/routes/mealPlans.js
> fix: ical throwing 500

- packages/trpc/src/factories/recipeFactory.ts
- packages/trpc/src/procedures/recipes/createRecipe.spec.ts
- packages/trpc/src/procedures/recipes/deleteRecipe.spec.ts
- packages/trpc/src/procedures/recipes/getRecipe.spec.ts
- packages/trpc/src/procedures/recipes/getRecipeByTitle.spec.ts
- packages/trpc/src/procedures/recipes/getRecipes.spec.ts
- packages/trpc/src/testutils.ts
adding unit tests for getRecipes
please let me know if I missed any cases
also note, timeout is for my potato setup :)
thank you!
> test: unit tests on recipes

- packages/frontend/src/app/services/http-error-handler.service.ts
- packages/frontend/src/assets/i18n/en-us.json
> feat: display a disruptive error when critical errors occur

- packages/frontend/src/app/pages/home-search-popover/home-search-filter-popover.page.html
- packages/frontend/src/app/pages/home-search-popover/home-search-filter-popover.page.ts
- packages/frontend/src/app/pages/home/home.page.ts
- packages/frontend/src/app/pages/resettable-select-popover/resettable-select-popover.page.html
- packages/frontend/src/app/pages/resettable-select-popover/resettable-select-popover.page.ts
- packages/frontend/src/assets/i18n/en-us.json
- packages/prisma/src/types/labelSummary.ts
- packages/trpc/src/index.ts
- packages/trpc/src/procedures/labels/getAllVisibleLabels.ts
- packages/trpc/src/procedures/labels/getLabelsByUserId.ts
- packages/util/server/src/db/getRecipesWithConstraints.ts
- packages/util/server/src/db/getVisibleLabels.ts
- packages/util/server/src/db/getVisibleProfileItems.ts
- packages/util/server/src/db/index.ts
- packages/util/server/src/general/groupProfileItemsByUserId.ts
> feat: filter by label on shared collections

- packages/frontend/src/app/pages/recipe-components/add-recipe-to-meal-plan-modal/add-recipe-to-meal-plan-modal.page.ts
- packages/frontend/src/app/pages/recipe-components/add-recipe-to-shopping-list-modal/add-recipe-to-shopping-list-modal.page.ts
> fix: select last used shopping list/meal plan rather than first

- packages/util/server/src/ml/textToRecipe.ts
> fix: ml sometimes translating imported text

- docker-compose.yml
- kube/configs/api-beta.yml
- kube/configs/api.yml
- packages/backend/src/bin/www.ts
- packages/frontend/src/app/pages/messaging-components/assistant/assistant.page.html
- packages/frontend/src/app/pages/recipe-components/edit-recipe/edit-recipe.page.html
- packages/frontend/src/app/pages/recipe-components/edit-recipe/edit-recipe.page.ts
- packages/frontend/src/app/services/feature-flag.service.ts
- packages/frontend/src/assets/i18n/en-us.json
- packages/trpc/src/procedures/ml/getRecipeFromText.ts
- packages/util/server/src/general/isFirebaseAvailable.ts
- packages/util/server/src/ml/assistant.ts
- packages/util/server/src/ml/ocr.ts
- packages/util/server/src/ml/ocrImageToRecipe.ts
- packages/util/server/src/ml/openai.ts
- packages/util/server/src/ml/pdfToRecipe.ts
- packages/util/server/src/ml/textToRecipe.ts
- packages/util/server/src/ml/visionToRecipe.ts
- packages/util/server/src/ml/visionToText.ts
> feat: enable assistant for selfhost

- packages/backend/src/app.ts
> fix: firefox browser extension CORS

- packages/trpc/src/procedures/labels/createLabel.spec.ts
- packages/trpc/src/procedures/labels/deleteLabel.spec.ts
- packages/trpc/src/procedures/labels/getLabels.spec.ts
- packages/trpc/src/procedures/labels/getLabelsByUserId.spec.ts
- packages/trpc/src/procedures/labels/updateLabel.spec.ts
- packages/trpc/src/procedures/recipes/getUniqueRecipeTitle.spec.ts
I have not finished all tests in get labels, will finish them later.
> various tests create/delete/get labels

- README.md
Links to DeepL and G Translate
> Update README.md (add links)

- .circleci/config.yml
- nx.json
- packages/trpc/src/procedures/labels/createLabel.spec.ts
- packages/trpc/src/procedures/labels/deleteLabel.spec.ts
- packages/trpc/src/procedures/labels/getLabels.spec.ts
- packages/trpc/src/procedures/labels/getLabelsByUserId.spec.ts
- packages/trpc/src/procedures/labels/updateLabel.spec.ts
- packages/trpc/src/procedures/recipes/getUniqueRecipeTitle.spec.ts
- packages/webextension-v3/src/action/action.html
- packages/webextension-v3/src/action/action.js
- packages/webextension-v3/src/inject/inject.js
Closes #1436 
Closes #1435
Closes #992
> fix: various webextension issues

- packages/frontend/src/app/app.component.ts
- packages/frontend/src/app/pages/meal-plan-components/meal-plan/meal-plan.page.ts
- packages/frontend/src/app/pages/recipe-components/recipe/recipe.page.ts
- packages/frontend/src/app/pages/shopping-list-components/shopping-list/shopping-list.page.ts
- packages/frontend/src/assets/i18n/en-us.json
If this looks good I can update the Shopping list, Menu, and whatever other pages you think might benefit.  
https://github.com/user-attachments/assets/0525755c-a5bc-4793-a678-8d706ab3c8f2
Closes #1443
> feat: Update Page Title When viewing recipe

- package-lock.json
- package.json
- packages/frontend/project.json
> fix: tile view on small screens

- packages/frontend/src/app/components/select-ingredients/select-ingredients.component.ts
> #1826: Make ignore list for shopping list case insensitive
